"""Internal backend contract used by :class:`he_sdk.HESession`."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, Sequence

from he_sdk.capabilities import CapabilitySet
from he_sdk.config import CKKSConfig


class HEBackend(Protocol):
    name: str
    engine_version: str
    context_id: str
    key_bundle_id: str
    capabilities: CapabilitySet
    has_secret_key: bool

    def __init__(self, config: CKKSConfig) -> None: ...

    def encrypt(self, values: Sequence[float]) -> Any: ...

    def decrypt(self, encrypted: Any, length: int) -> list[float]: ...

    def add(self, left: Any, right: Any) -> Any: ...

    def subtract(self, left: Any, right: Any) -> Any: ...

    def multiply(self, left: Any, right: Any) -> Any: ...

    def square(self, encrypted: Any) -> Any: ...

    def sum(self, encrypted: Any, valid_count: int) -> Any: ...

    def mean(self, encrypted: Any, valid_count: int) -> Any: ...

    def variance(self, encrypted: Any, valid_count: int) -> Any: ...

    def create_result_recipient(self) -> tuple[str, Any, Any]: ...

    def reencrypt_for_recipient(
        self, encrypted: Any, recipient_public_key: Any
    ) -> Any: ...

    def decrypt_for_recipient(
        self, encrypted: Any, recipient_secret_key: Any, length: int
    ) -> list[float]: ...

    def serialize_public_key(self, public_key: Any, path: Path) -> None: ...

    def deserialize_public_key(self, path: Path) -> Any: ...

    def export_public_material(self, directory: Path) -> None: ...

    def serialize_ciphertext(self, encrypted: Any, path: Path) -> None: ...

    def deserialize_ciphertext(self, path: Path) -> Any: ...

    def close(self) -> None: ...
